branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: change
  email: false
language: node_js
node_js:
  - "0.10"

before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install"
# Create an installation.
  - "git clone git://github.com/mozilla/marketplace-template.git"
  - "cd marketplace-template"
  - "npm install -g ../"
  - "make init"
  - "rm -rf node_modules/commonplace"
  - "npm install ../"
  - "make update"
script:
# Lint the installation.
  - "commonplace lint"
# Start the webserver.
  - "make serve &"
  - "sleep 3"
# Run the unit tests.
  - "DISPLAY=:99.0 node_modules/.bin/casperjs test ../test"
# Generate include files and test that they are there.
  - "make build"
  - "test -f src/media/js/include.js"
# Delete the include files and test that they are gone.
  - "make clean"
  - "test ! -f src/media/js/include.js"
